# Generated by Django 4.0.3 on 2022-04-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newshopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
